name: Deploy to DigitalOcean
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          debug: true
          script: |
            cd /root/my-directus-project
            git stash
            git pull origin main
            npm install
            cp ecosystem.config.js .
            PM2_HOME=/root/.pm2 pm2 delete all || true
            PM2_HOME=/root/.pm2 pm2 start ecosystem.config.js
            PM2_HOME=/root/.pm2 pm2 save