name: Deploy to DigitalOcean

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      env:
        DB_CLIENT: ${{ secrets.DB_CLIENT }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        DO_SPACES_ENDPOINT: ${{ secrets.DO_SPACES_ENDPOINT }}
        DO_SPACES_KEY: ${{ secrets.DO_SPACES_KEY }}
        DO_SPACES_SECRET: ${{ secrets.DO_SPACES_SECRET }}
        KEY: ${{ secrets.KEY }}
        SECRET: ${{ secrets.SECRET }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      with:
        host: 161.35.70.99
        username: root
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd /path/to/your/project
          git pull origin main
          npm install
          npm run build
          pm2 restart directus